# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('necessary_works', models.CharField(max_length=230, null=True)),
                ('report', models.TextField(max_length=2140, null=True)),
                ('review', models.TextField(max_length=1540, null=True)),
                ('mark', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('teacher', models.CharField(max_length=60, null=True)),
                ('director', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('group', models.CharField(max_length=10, null=True)),
                ('edu_profile', models.CharField(max_length=50, null=True)),
                ('contract', models.BooleanField(default=False)),
                ('degree', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('practice', models.ManyToManyField(to='generator.Practice')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('company', models.CharField(max_length=60, null=True)),
                ('address', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='practice',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generator.Type'),
        ),
        migrations.AddField(
            model_name='pass',
            name='practice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generator.Practice'),
        ),
        migrations.AddField(
            model_name='pass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Student'),
        ),
        migrations.AddField(
            model_name='individualtask',
            name='practice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='практика', to='generator.Student'),
        ),
        migrations.AddField(
            model_name='individualtask',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='студент', to='generator.Student'),
        ),
        migrations.AddField(
            model_name='diary',
            name='practice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.Practice'),
        ),
        migrations.AddField(
            model_name='diary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Student'),
        ),
        migrations.AddField(
            model_name='dates',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Student'),
        ),
    ]
