# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20170712_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deanery',
            name='group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group_link',
        ),
    ]
