# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20170713_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('EDU', 'Учебная'), ('PROD', 'Производственная'), ('DIP', 'Преддипломная')], default='EDU', max_length=20),
        ),
    ]
