# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_auto_20170714_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
