# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='practice',
            field=models.ManyToManyField(blank=True, to='generator.Practice'),
        ),
    ]
