# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_student_course'),
        ('generator', '0005_auto_20170714_0011'),
    ]

    operations = [
    ]
