# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_auto_20170714_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='company',
        ),
        migrations.AddField(
            model_name='type',
            name='address',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='company',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
