# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_auto_20170714_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Practice'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
