# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0012_auto_20170714_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='address',
        ),
        migrations.RemoveField(
            model_name='type',
            name='company',
        ),
        migrations.AddField(
            model_name='practice',
            name='address',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='company',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('Учебная', 'Учебная'), ('Производственная', 'Производственная'), ('Преддипломная', 'Преддипломная')], default='Учебная', max_length=20),
        ),
    ]
