# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_auto_20170714_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='type',
            field=models.CharField(choices=[('Учебная', 'Educational'), ('Произведственная', 'Factory'), ('Преддипломная', 'Preddiplomnaya')], default='Учебная', max_length=20),
        ),
    ]
