# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_auto_20170714_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='type',
            field=models.CharField(choices=[('Учебная', 'Учебная'), ('Произведственная', 'Производственная'), ('Преддипломная', 'Преддипломная')], default='Учебная', max_length=20),
        ),
    ]
