# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_auto_20170715_1825'),
        ('generator', '0016_auto_20170714_1723'),
    ]

    operations = [
    ]
