# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_merge_20170717_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtask',
            name='practice',
        ),
        migrations.AddField(
            model_name='individualtask',
            name='practice_type',
            field=models.CharField(choices=[('Учебная', 'Учебная'), ('Произведственная', 'Производственная'), ('Преддипломная', 'Преддипломная')], default='Учебная', max_length=20),
        ),
        migrations.AddField(
            model_name='pass',
            name='company_director',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
