# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_auto_20170717_0818'),
        ('generator', '0017_merge_20170716_1919'),
    ]

    operations = [
    ]
