# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0019_merge_20170717_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualTaskDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.Practice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.Practice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='diary',
            name='description',
        ),
        migrations.AddField(
            model_name='diaryrecord',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.Diary'),
        ),
        migrations.AddField(
            model_name='individualtask',
            name='doc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.IndividualTaskDoc'),
        ),
    ]
