# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0021_auto_20170717_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='date_from',
            field=models.DateField(null=True, verbose_name='start'),
        ),
        migrations.AddField(
            model_name='practice',
            name='date_to',
            field=models.DateField(null=True, verbose_name='end'),
        ),
    ]
