# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0023_merge_20170718_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtask',
            name='student',
        ),
        migrations.AddField(
            model_name='individualtask',
            name='dateFrom',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='individualtask',
            name='dateTo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='individualtask',
            name='desc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='individualtask',
            name='doc',
        ),
        migrations.AddField(
            model_name='individualtask',
            name='doc',
            field=models.ManyToManyField(to='generator.IndividualTaskDoc'),
        ),
        migrations.AlterField(
            model_name='student',
            name='practice',
            field=models.ManyToManyField(to='generator.Practice'),
        ),
    ]
