# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0025_auto_20170718_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='contract_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pass',
            name='contract_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='practice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.Practice'),
        ),
    ]
