# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0026_auto_20170718_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.Student'),
        ),
    ]
