# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0025_diaryrecord_date'),
        ('generator', '0028_auto_20170718_1235'),
    ]

    operations = [
    ]
