# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0028_auto_20170718_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtaskdoc',
            name='practice',
        ),
        migrations.AddField(
            model_name='practice',
            name='ind_task',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.IndividualTask'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='practice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.Practice'),
        ),
    ]
