# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0029_auto_20170718_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='ind_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.IndividualTask'),
        ),
    ]
