# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0029_merge_20170719_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtaskdoc',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='individualtaskdoc',
            name='student',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='student',
        ),
        migrations.RemoveField(
            model_name='report',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='report',
            name='student',
        ),
        migrations.RemoveField(
            model_name='individualtask',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.AddField(
            model_name='individualtask',
            name='student',
            field=models.ManyToManyField(to='generator.Student'),
        ),
        migrations.AddField(
            model_name='practice',
            name='chief',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='necessary_works',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mark',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='report',
            field=models.TextField(max_length=1429, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='review',
            field=models.TextField(max_length=1034, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='practice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.Practice'),
        ),
        migrations.AlterField(
            model_name='diaryrecord',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_from',
            field=models.DateField(null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_to',
            field=models.DateField(null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='student',
            name='edu_profile',
            field=models.CharField(choices=[('09.03.04 Программная инженерия', '09.03.04 Программная инженерия'), ('09.03.03 Прикладная информатика', '09.03.03 Прикладная информатика')], default='09.03.04 Программная инженерия', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='IndividualTaskDoc',
        ),
        migrations.DeleteModel(
            name='Pass',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
