# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0031_auto_20170718_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='ind_task',
        ),
        migrations.AddField(
            model_name='practice',
            name='ind_task',
            field=models.ManyToManyField(null=True, to='generator.IndividualTask'),
        ),
    ]
