# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0033_individualtaskdoc_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtaskdoc',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='individualtaskdoc',
            name='student',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='student',
        ),
        migrations.RemoveField(
            model_name='report',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='report',
            name='student',
        ),
        migrations.RemoveField(
            model_name='individualtask',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='ind_task',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.AddField(
            model_name='diaryrecord',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='practice',
            name='chief',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='necessary_works',
            field=models.CharField(max_length=230, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mark',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='report',
            field=models.TextField(max_length=2140, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='review',
            field=models.TextField(max_length=1540, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_from',
            field=models.DateField(null=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='date_to',
            field=models.DateField(null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='student',
            name='edu_profile',
            field=models.CharField(choices=[('09.03.04 Программная инженерия', '09.03.04 Программная инженерия'), ('09.03.03 Прикладная информатика', '09.03.03 Прикладная информатика')], default='09.03.04 Программная инженерия', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='IndividualTaskDoc',
        ),
        migrations.DeleteModel(
            name='Pass',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
