# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0034_auto_20170718_1747'),
        ('generator', '0025_diaryrecord_date'),
    ]

    operations = [
    ]
