# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0035_merge_20170719_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryrecord',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='chief',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='necessary_works',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='report',
            field=models.TextField(max_length=1429, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='review',
            field=models.TextField(max_length=1034, null=True),
        ),
    ]
