# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0036_auto_20170719_1326'),
        ('generator', '0030_auto_20170719_1449'),
    ]

    operations = [
    ]
